# Generated by Django 5.2.5 on 2025-08-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mugure Cyber Services', max_length=100)),
                ('tagline', models.CharField(default='Your Trusted Cyber Cafe in Gatundu North', max_length=200)),
                ('description', models.TextField(default='Providing reliable internet, printing, and online services to the Kamwangi community since 2020.')),
                ('phone', models.CharField(default='+254 712 345 678', max_length=20)),
                ('email', models.EmailField(default='info@mugurecyber.com', max_length=254)),
                ('address', models.TextField(default='Kamwangi Market, Gatundu North')),
                ('whatsapp_number', models.CharField(default='254712345678', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('hero_title', models.CharField(default='Your Trusted Cyber Cafe in Gatundu North', max_length=200)),
                ('hero_subtitle', models.TextField(default='Providing reliable internet, printing, and online services to the Kamwangi community since 2020.')),
                ('about_title', models.CharField(default='About Mugure Cyber Services', max_length=200)),
                ('about_content', models.TextField(default='We have been serving the Kamwangi community with reliable cyber services since 2020.')),
                ('contact_title', models.CharField(default='Get in Touch', max_length=200)),
                ('contact_subtitle', models.TextField(default='Ready to help with all your digital needs')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
